### ISSUE TITLE
`new` fails with existing directory

### ISSUE THREAD

**Issue by colepeters** [enhance-dev/cli#14]
Attempting to create a new Enhance app with an existing directory fails:

```shell
❯ npx @enhance/cli@latest new ./existing-directory -y
Error: Plugin errors:
- Cannot find plugin 'enhance/arc-plugin-enhance'! Are you sure you have installed or created it correctly?
- Cannot find plugin 'enhance/arc-image-plugin'! Are you sure you have installed or created it correctly?
```

We should be able to init a new app with an existing directory (at least if it's empty, maybe with other conditions in mind)?

**Comment by macdonst** [comment]
My proposed solution for this would be the init command https://github.com/enhance-dev/cli/commit/0e8e4e1f9b8acbbfe8f8ef6346378226145e1212

**Comment by tbeseda** [comment]
fwiw, I know we don't want to stomp on anything existing. but maybe if the folder doesn't have a package.json at all, we go ahead and init in there. 

at least: `if the dir exists` : report a nice error

**Comment by macdonst** [comment]
Addressed with `npx @enhance/cli@latest init -y` to bootstrap an Enhance project in an existing directory.
